### ISSUE TITLE
Errors when trying to run test after intitial clone

### ISSUE THREAD

**Issue by c1505** [learn-co-curriculum/sinatra-basic-sessions-lab#4]
OS X 10.11.3  
Ruby 2.2.1

tried to bundle install and bundle update.  neither fixed the issue.
Worked on cloud9 for me though.  

 error :
/Users/Corey/dev/sinatra/sinatra-basic-sessions-lab-v-000/spec/spec_helper.rb:6:in `block in <top (required)>': uninitialized constant Capybara::DSL (NameError)
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core.rb:97:in`configure'
    from /Users/Corey/dev/sinatra/sinatra-basic-sessions-lab-v-000/spec/spec_helper.rb:5:in `<top (required)>'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in`require'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `block in requires='
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in`each'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `requires='
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:109:in`block in process_options_into'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:108:in `each'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:108:in`process_options_into'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:21:in `configure'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:105:in`setup'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in`run'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/exe/rspec:4:in`<top (required)>'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `load'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/bin/rspec:23:in`<main>'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Corey/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in`<main>'

**Comment by AnnJohn** [comment]
Hi @c1505 sorry about the trouble. We'll look into this but for immediate help can you use the Ask a Question tool in Learn and someone will get back to you right away. Thanks.

**Comment by victhevenot** [comment]
hey @c1505,

I can't seem to recreate this issue.

Could you try changing your  `spec/spec_helper.rb` to look like the code below and let me know if that fixes things

```
ENV["SINATRA_ENV"] = "test"
require_relative '../config/environment.rb'
require 'rack/test'
require 'capybara'
require 'capybara/dsl'
require 'capybara/rspec'


RSpec.configure do |config|
  config.include Capybara::DSL
  config.include Rack::Test::Methods
  config.order = 'default'
end

def app
  Rack::Builder.parse_file('config.ru').first
end

Capybara.app = app

def session
  last_request.env['rack.session']
end
```

**Comment by c1505** [comment]
That fixes it for me @vicfriedman .  Not sure why it worked for me in one environment and not another before the fix.

**Comment by victhevenot** [comment]
Awesome, thanks for that insight! going to submit a PR with this updated spec_helper
